server:
  port: 8887
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: http://localhost:9999
          predicates:
            - Path=/games/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@userKeyResolver}'
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 2